export const PRODUCT_CONSTANTS_REQUEST = 'PRODUCT_CONSTANT_REQUEST';
export const PRODUCT_CONSTANTS_SUCCESS = 'PRODUCT_CONSTANT_SUCCESS';
export const PRODUCT_CONSTANTS_FAIL = 'PRODUCT_CONSTANT_FAIL';

